### ISSUE TITLE
Need help: Contract compilation fails 

### ISSUE THREAD

**Issue by lmahanand** [dydxprotocol/solo#416]
I am trying to build the solo smart contracts but it seems to be failing while compiling openzeppelin-solidity/contracts/utils/ReentrancyGuard.sol.

```
[ec2-user@ip-172-31-42-73 solo]$ npm run build

> @dydxprotocol/solo@0.33.0 build /home/ec2-user/projects/solo
> npm run compile && npm run copy_tew && npm run build:wrappers && npm run clean_contract_json


> @dydxprotocol/solo@0.33.0 compile /home/ec2-user/projects/solo
> truffle compile


Compiling your contracts...
===========================
> Compiling ./contracts/Migrations.sol
> Compiling ./contracts/external/helpers/OnlySolo.sol
> Compiling ./contracts/external/interestsetters/DoubleExponentInterestSetter.sol
> Compiling ./contracts/external/interestsetters/PolynomialInterestSetter.sol
> Compiling ./contracts/external/interfaces/IMakerOracle.sol
> Compiling ./contracts/external/interfaces/IOasisDex.sol
> Compiling ./contracts/external/lib/TypedSignature.sol
> Compiling ./contracts/external/multisig/DelayedMultiSig.sol
> Compiling ./contracts/external/multisig/MultiSig.sol
> Compiling ./contracts/external/multisig/PartiallyDelayedMultiSig.sol
> Compiling ./contracts/external/oracles/DaiPriceOracle.sol
> Compiling ./contracts/external/oracles/UsdcPriceOracle.sol
> Compiling ./contracts/external/oracles/WethPriceOracle.sol
> Compiling ./contracts/external/proxies/LiquidatorProxyV1ForSoloMargin.sol
> Compiling ./contracts/external/proxies/PayableProxyForSoloMargin.sol
> Compiling ./contracts/external/proxies/SignedOperationProxy.sol
> Compiling ./contracts/external/traders/CanonicalOrders.sol
> Compiling ./contracts/external/traders/DaiMigrator.sol
> Compiling ./contracts/external/traders/Expiry.sol
> Compiling ./contracts/external/traders/ExpiryV2.sol
> Compiling ./contracts/external/traders/LimitOrders.sol
> Compiling ./contracts/external/traders/Refunder.sol
> Compiling ./contracts/external/traders/StopLimitOrders.sol
> Compiling ./contracts/protocol/Admin.sol
> Compiling ./contracts/protocol/Getters.sol
> Compiling ./contracts/protocol/Operation.sol
> Compiling ./contracts/protocol/Permission.sol
> Compiling ./contracts/protocol/SoloMargin.sol
> Compiling ./contracts/protocol/State.sol
> Compiling ./contracts/protocol/impl/AdminImpl.sol
> Compiling ./contracts/protocol/impl/OperationImpl.sol
> Compiling ./contracts/protocol/interfaces/IAutoTrader.sol
> Compiling ./contracts/protocol/interfaces/ICallee.sol
> Compiling ./contracts/protocol/interfaces/IErc20.sol
> Compiling ./contracts/protocol/interfaces/IExchangeWrapper.sol
> Compiling ./contracts/protocol/interfaces/IInterestSetter.sol
> Compiling ./contracts/protocol/interfaces/IPriceOracle.sol
> Compiling ./contracts/protocol/lib/Account.sol
> Compiling ./contracts/protocol/lib/Actions.sol
> Compiling ./contracts/protocol/lib/Cache.sol
> Compiling ./contracts/protocol/lib/Decimal.sol
> Compiling ./contracts/protocol/lib/Events.sol
> Compiling ./contracts/protocol/lib/Exchange.sol
> Compiling ./contracts/protocol/lib/Interest.sol
> Compiling ./contracts/protocol/lib/Math.sol
> Compiling ./contracts/protocol/lib/Monetary.sol
> Compiling ./contracts/protocol/lib/Require.sol
> Compiling ./contracts/protocol/lib/Storage.sol
> Compiling ./contracts/protocol/lib/Time.sol
> Compiling ./contracts/protocol/lib/Token.sol
> Compiling ./contracts/protocol/lib/Types.sol
> Compiling ./contracts/testing/ErroringOmiseToken.sol
> Compiling ./contracts/testing/ErroringToken.sol
> Compiling ./contracts/testing/OmiseToken.sol
> Compiling ./contracts/testing/TestAutoTrader.sol
> Compiling ./contracts/testing/TestCallee.sol
> Compiling ./contracts/testing/TestCounter.sol
> Compiling ./contracts/testing/TestDoubleExponentInterestSetter.sol
> Compiling ./contracts/testing/TestInterestSetter.sol
> Compiling ./contracts/testing/TestLib.sol
> Compiling ./contracts/testing/TestMakerOracle.sol
> Compiling ./contracts/testing/TestOasisDex.sol
> Compiling ./contracts/testing/TestPolynomialInterestSetter.sol
> Compiling ./contracts/testing/TestPriceOracle.sol
> Compiling ./contracts/testing/TestSimpleCallee.sol
> Compiling ./contracts/testing/TestSoloMargin.sol
> Compiling ./contracts/testing/TestToken.sol
> Compiling ./contracts/testing/TokenA.sol
> Compiling ./contracts/testing/TokenB.sol
> Compiling ./contracts/testing/TokenC.sol
> Compiling canonical-weth/contracts/WETH9.sol
> Compiling openzeppelin-solidity/contracts/math/SafeMath.sol
> Compiling openzeppelin-solidity/contracts/ownership/Ownable.sol
> Compiling openzeppelin-solidity/contracts/utils/ReentrancyGuard.sol
Unable to find image 'ethereum/solc:0.5.7' locally
0.5.7: Pulling from ethereum/solc
4b32e6eb57fa: Pulling fs layer
4b32e6eb57fa: Download complete
4b32e6eb57fa: Pull complete
Digest: sha256:35724598a6e6a60c87eec1be5842fef06b6d267d49b849ae7d72a832a0f129ca
Status: Downloaded newer image for ethereum/solc:0.5.7
Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (internal/child_process.js:1045:20)
    at spawnSync (child_process.js:597:24)
    at execSync (child_process.js:642:15)
    at Object.compile (/home/ec2-user/projects/solo/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/loadingStrategies/Docker.js:19:1)
    at invokeCompiler (/home/ec2-user/projects/solo/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:251:1)
    at run (/home/ec2-user/projects/solo/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:29:40)
    at compile (/home/ec2-user/projects/solo/node_modules/truffle/build/webpack:/packages/compile-solidity/new/index.js:23:1)
    at AsyncFunction.compile.with_dependencies (/home/ec2-user/projects/solo/node_modules/truffle/build/webpack:/packages/compile-solidity/new/index.js:106:1)
    at compile.necessary (/home/ec2-user/projects/solo/node_modules/truffle/build/webpack:/packages/compile-solidity/new/index.js:62:1)
    at /home/ec2-user/projects/solo/node_modules/truffle/build/webpack:/packages/workflow-compile/new/index.js:50:1
    at async Promise.all (index 0)
    at compile (/home/ec2-user/projects/solo/node_modules/truffle/build/webpack:/packages/workflow-compile/new/index.js:37:1)
    at Object.compile (/home/ec2-user/projects/solo/node_modules/truffle/build/webpack:/packages/workflow-compile/new/index.js:80:52)
Truffle v5.1.12 (core: 5.1.12)
Node v13.9.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @dydxprotocol/solo@0.33.0 compile: `truffle compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @dydxprotocol/solo@0.33.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2020-02-29T16_03_58_493Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @dydxprotocol/solo@0.33.0 build: `npm run compile && npm run copy_tew && npm run build:wrappers && npm run clean_contract_json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @dydxprotocol/solo@0.33.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2020-02-29T16_03_58_512Z-debug.log


```

**Comment by Pet3ris** [comment]
@lmahanand I'm experiencing the same issue - any tips to overcome?

**Comment by Pet3ris** [comment]
Changing node version to `10.16.0` worked.
