### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by guotie** [dydxprotocol/solo#499]
```
node_modules/@dydxprotocol/solo/dist/build/wrappers/CanonicalOrders.d.ts:6:10 - error TS2614: Module '"../../../../../web3/types"' has no exported member 'Callback'. Did you mean to use 'import Callback from "../../../../../web3/types"' instead?

6 import { Callback, EventLog } from "web3/types";
           ~~~~~~~~

node_modules/@dydxprotocol/solo/dist/build/wrappers/CanonicalOrders.d.ts:6:20 - error TS2614: Module '"../../../../../web3/types"' has no exported member 'EventLog'. Did you mean to use 'import EventLog from "../../../../../web3/types"' instead?

6 import { Callback, EventLog } from "web3/types";
                     ~~~~~~~~
```

**Comment by guotie** [comment]
compile error:

```
import { Solo, Networks } from '@dydxprotocol/solo'
         ^^^^
SyntaxError: The requested module '@dydxprotocol/solo' does not provide an export named 'Solo'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:164:24)

```

**Comment by anyshy** [comment]
yarn add @types/web3
